### ISSUE TITLE
What happens if someone uses a version number less than the current?

### ISSUE THREAD

**Issue by mtscout6** [theamazingfedex/tdd_extw#13]

**Comment by theamazingfedex** [comment]
I removed the option to plug in dynamic values for the version number. Now to update 1.0.0, call esbump -M -m -p -P=beta to update the version to 2.1.1-beta.0

**Comment by mtscout6** [comment]
Generally you wouldn't want a version bump to skip that many versions. You should only be incrementing one number per bump.

**Comment by theamazingfedex** [comment]
calling esbump with all of those arguments would bump the version as shown, however those arguments are optional, I only included them to demonstrate functionality.
