### ISSUE TITLE
With Promises you can use a general catch handler

### ISSUE THREAD

**Issue by mtscout6** [theamazingfedex/tdd_extw#22]
https://github.com/theamazingfedex/tdd_extw/blob/master/src/app.js#L28-L64

Also a few other things:
- Arrow functions with one argument don't need parenthesis
- Arrow functions with a single statement implicitly return the value of that statement.

Could be:

```
  loadFile(filename)
    .then(fileData => bumpVersion(fileData, vargs))
    .then(bump => {
      version = bump.version;
      return saveFile(bump, version);
    })
    .then(() => commitToLocalGit(version))
    .then(() => addGitTag(version))
    .then(pushToRemote())
    .then(() => 0)
    .catch(err => 1);
```

**Comment by theamazingfedex** [comment]
Awesome, thanks for this, it cleaned up my code nicely.
