### ISSUE TITLE
Receiving error when running 

### ISSUE THREAD

**Issue by mikeerickson** [theamazingfedex/tdd_extw#28]
I am trying this puppy out and it always throws an error

```
 $ esbump -M
env: node\r: No such file or directory
```

I have confirmed it is installed correctly

```
$ esbump --which

esbump -> ../lib/node_modules/semver-esbump/bin/initializer.js

```

I have tried to reinstall, but no luck

```
$ npm i -g esbump
```

**Comment by mikeerickson** [comment]
Note:  I have also tried instructions for this package

```
 $ sudo npm install -g semverbump
Password:
npm WARN lifecycle semverbump@1.0.5~preinstall: cannot run in wd %s %s (wd=%s) semverbump@1.0.5 npm run build /usr/local/lib/node_modules/.staging/semverbump-783c19bb
/usr/local/bin/semverbump -> /usr/local/lib/node_modules/semverbump/bin/initializer.js
/usr/local/lib
└─┬ semverbump@1.0.5
  ├── cltags@0.0.2
  └── shelljs@0.5.3

 ~/Documents/Projects/webpack/plugins   master 
 $ semverbump
env: node\r: No such file or directory
 ✘  ~/Documents/Projects/webpack/plugins   master 
 $ semverbump --help
env: node\r: No such file or directory
 ✘  ~/Documents/Projects/webpack/plugins   master 
 $
```

**Comment by theamazingfedex** [comment]
Wow, I had forgotten about this project. It was something I did as an intern in college, and I think I ended up finishing it without pushing up here. This project is pretty much dead, but if you want a good semantic versioning node package, check out `semver` [[GitHub]](https://github.com/npm/node-semver) [[NPM]](https://www.npmjs.com/package/semver)

**Comment by mikeerickson** [comment]
@theamazingfedex Well, that surely explains it :-)   I am using the semver module, however, it is not what I am looking for in that it does not work as CLI.   

Thanks for feedback though, I am just going to spend an hour and craft my own (I was looking for easier way out)   :-)

**Comment by theamazingfedex** [comment]
Ahaa. Well you've inspired me to try to fix this. I just installed it myself and am getting this error:

```
~\AppData\Roaming\npm\node_modules\semverbump\lib\app.js:3
import { parseArgs, loadFile, bumpVersion, saveFile, commitToLocalGit, addGitTag, pushToRemote } from "./esbump-toolkit.js";
^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (~\AppData\Roaming\npm\node_modules\semverbump\bin\initializer.js:3:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

Working on it now

**Comment by mikeerickson** [comment]
@theamazingfedex did you get it figured out?

**Comment by mikeerickson** [comment]
@theamazingfedex if not, no problem.  I will just roll my own.  But if you happen to make it work, then I wont bother :-)

**Comment by theamazingfedex** [comment]
Nah, for some reason it's failing to read the package.json, and it's not even giving me good reasons why, so I've conceded. You're welcome to fork this repository as a starting point though.

**Comment by mikeerickson** [comment]
@theamazingfedex will do :-)
